### ISSUE TITLE
SystemArgumentException: taskToken

### ISSUE THREAD

**Issue by alexzm1** [gurmitteotia/guflow#23]
We recently got an exception going on one of our ActivityHosts logs, this is being printed in our log files periodically

System.ArgumentException: taskToken   
at Guflow.Ensure.That[T](Boolean condition, Func`1 exception)
at Guflow.Domain.SendActivityResponseAsync(String taskToken, ActivityResponse response, CancellationToken cancellationToken)
at Guflow.RetryableFunc.ExecuteAsync(Func`1 func)

**Comment by gurmitteotia** [comment]
It is a bug. It was a quick fix. I have released a new version- [1.1.26](https://www.nuget.org/packages/Guflow/1.1.26)

**Comment by alexzm1** [comment]
Just verified the fix and there are no more Error log statements with that exception.

Thanks!
